import Head from "next/head";
import { Html } from "next/document";
import MainPage from "../components/mainPage/mainPage";
import SpeakerPage from "../components/speakerPage/speakerPage";
// import { isMobile } from "react-device-detect";



export default function Home() {
  return (
    <Html >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-primary text-black font-dosis ">
        <MainPage />
        <SpeakerPage />
      </main>
    </Html>
  );
}
