import Head from "next/head";

import MainPage from "../components/mainPage/mainPage";
import SpeakerPage from "../components/speakerPage/speakerPage";
import TimelinePage from "../components/timelinePage/timelinePage";

// import { isMobile } from "react-device-detect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nebula</title>
        <meta name="description" content="Generated by Nebula" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nebula.ico" />
      </Head>
      <main className="bg-primary text-black font-dosis ">
        <MainPage />

        <SpeakerPage />

        <TimelinePage />
       

      </main>
    </>
  );
}
